filter_mode = "global"
filter_mode_shell_up_key_binding = "directory"
invert = false
enter_accept = true
prefers_reduced_motion = true

[keys]
accept_past_line_start = true

[sync]
records = true

[theme]
name = "catppuccin-mocha-green"
